#!/bin/sh

set -eux

rxrand="$(base64 < /dev/random | tr -d '/+=' | head -c 10)"

opwd="$(pwd)"

mkdir /tmp/websvgtex-$rxrand
cd /tmp/websvgtex-$rxrand

cat >m.tex <<EOF
\documentclass[preview]{standalone}
\usepackage{amsmath}
\begin{document}
EOF

cat /dev/stdin >>m.tex

cat >>m.tex <<EOF
\end{document}
EOF

{ set +u; } 2>/dev/null
if [ -z "$1" ]
then
	export_filename="m.svg"
else
	export_filename="$1"
fi
{ set -u; } 2>/dev/null

latex m.tex
latex m.tex
dvips m.dvi
inkscape m.ps --export-plain-svg --export-filename="$export_filename"

mv "$export_filename" "$opwd"
